// js/pools/football.js
// Shared pool of generic football words used by the password widget when a page's
// Config_JSON has "topic": "football". Keep entries lowercase, with no apostrophes,
// spaces or commas (hyphens are fine). Avoid anything tied to one club.
const FOOTBALL_POOL = [
  "ball", "football", "soccer", "corner", "penalty", "offside", "foul", "tackle", "header", "volley", "dribble",
  "cross", "pass", "shot", "goal", "save", "keeper", "striker", "winger", "midfield", "defender", "sweeper",
  "captain", "referee", "linesman", "whistle", "kickoff", "halftime", "fulltime", "extra-time", "stoppage",
  "throw-in", "goal-kick", "free-kick", "drop-ball", "advantage", "caution", "yellow-card", "red-card", "booking",
  "sending-off", "suspension", "appeal", "replay", "handball", "obstruction", "dissent", "dive", "tap-in", "one-two",
  "through-ball", "long-ball", "back-pass", "back-heel", "scissor-kick", "bicycle-kick", "overhead-kick", "chip",
  "lob", "curler", "screamer", "thunderbolt", "rocket", "daisy-cutter", "toe-poke", "slice", "shank", "miskick",
  "hoof", "punt", "clearance", "interception", "block", "deflection", "rebound", "parry", "punch", "tip-over",
  "fingertip", "claim", "switch", "layoff", "cutback", "overlap", "underlap", "nutmeg", "rabona", "panenka",
  "step-over", "flip-flap", "elastico", "cruyff-turn", "drag-back", "feint", "shimmy", "sidestep", "swerve", "bend",
  "dip", "knuckleball", "trivela", "instep", "half-volley", "glancing-header", "flick-on", "knock-down", "set-piece",
  "dead-ball", "wall", "barrier", "shirt-pull", "shove", "trip", "stamp", "elbow", "studs", "lunge",
  "sliding-tackle", "poach", "hat-trick", "brace", "equaliser", "winner", "leveller", "opener", "consolation",
  "own-goal", "golden-goal", "silver-goal", "away-goals", "aggregate", "penalties", "shootout", "spot-kick",
  "cup-tie", "league-table", "relegation", "promotion", "playoff", "six-pointer", "derby", "local-derby", "dogfight",
  "clean-sheet", "shutout", "comeback", "thriller", "stalemate", "draw", "goalless", "nil-nil", "rout", "thrashing",
  "hammering", "drubbing", "upset", "giant-killing", "banana-skin", "kick", "touch", "first-touch", "control",
  "trap", "cushion", "turn", "spin", "pivot", "burst", "sprint", "dart", "run", "channel-run", "overlap-run",
  "recovery-run", "track-back", "press", "harry", "hassle", "close-down", "mark", "shadow", "snuff", "shepherd",
  "usher", "shield", "hold-up", "back-to-goal", "lay-off", "flick", "nod", "glance", "steer", "guide", "place",
  "sidefoot", "passing-lane", "one-touch", "two-touch", "quick-free-kick", "short-corner", "near-post", "far-post",
  "six-yard", "top-corner", "bottom-corner", "postage-stamp", "stoppage-time", "added-time", "injury-time",
  "second-half", "first-half", "final-whistle", "pitch-invasion", "abandonment", "postponement", "rearranged",
  "fixture-list", "fixture", "congestion", "schedule", "matchday", "game-week", "gameweek", "goalkeeper",
  "custodian", "stopper", "libero", "centre-back", "full-back", "wing-back", "left-back", "right-back", "anchor",
  "playmaker", "regista", "maestro", "box-to-box", "number-ten", "false-nine", "target-man", "poacher", "finisher",
  "forward", "inside-forward", "outside-right", "outside-left", "centre-forward", "skipper", "vice-captain",
  "substitute", "sub", "super-sub", "bench", "twelfth-man", "youngster", "prodigy", "veteran", "journeyman",
  "legend", "hero", "talisman", "icon", "idol", "favourite", "fan", "supporter", "ultra", "steward", "groundsman",
  "physio", "kitman", "scout", "chairman", "director", "owner", "president", "manager", "gaffer", "boss", "coach",
  "assistant", "caretaker", "ref", "official", "assessor", "commentator", "pundit", "reporter", "mascot", "ballboy",
  "ballgirl", "trialist", "loanee", "academy-graduate", "captain-marvel", "dressing-room", "changing-room",
  "team-talk", "teamsheet", "squad-number", "shirt-number", "number-nine", "number-eleven", "number-seven",
  "number-one", "twin-strikers", "partnership", "pairing", "duo", "trio", "quartet", "spine", "backbone",
  "engine-room", "heartbeat", "linchpin", "fulcrum", "formation", "four-four-two", "four-three-three",
  "three-five-two", "diamond", "christmas-tree", "flat-back", "back-three", "back-five", "wing-play", "tiki-taka",
  "gegenpress", "counter-press", "high-press", "low-block", "mid-block", "park-the-bus", "catenaccio",
  "total-football", "route-one", "possession", "counter-attack", "transition", "overload", "width", "depth",
  "compactness", "offside-trap", "high-line", "sweeper-keeper", "zonal", "man-marking", "marking",
  "pressing-trigger", "rotation", "fluidity", "inverted", "half-space", "channels", "shuttle", "game-plan",
  "tactics", "tactician", "masterplan", "blueprint", "system", "philosophy", "identity", "style", "flair",
  "pragmatism", "discipline", "organisation", "shape", "structure", "balance", "tempo", "rhythm", "momentum",
  "pressure", "dominance", "intensity", "energy", "work-rate", "graft", "grit", "guts", "steel", "spirit", "belief",
  "desire", "hunger", "ambition", "pride", "passion", "character", "resilience", "bottle", "nerve", "composure",
  "shirt", "jersey", "kit", "shorts", "socks", "shinpads", "boots", "blades", "laces", "gloves", "armband", "badge",
  "crest", "sponsor", "stripes", "hoops", "halves", "sash", "away-kit", "home-kit", "third-kit", "goalpost",
  "crossbar", "upright", "net", "woodwork", "post", "touchline", "byline", "halfway", "centre-circle",
  "penalty-area", "six-yard-box", "box", "arc", "corner-flag", "dugout", "technical-area", "tunnel", "turnstile",
  "terrace", "stand", "floodlights", "scoreboard", "clock", "pitch", "turf", "grass", "bobble", "divot", "astroturf",
  "bench-area", "press-box", "directors-box", "league", "premier-league", "championship", "division",
  "first-division", "second-division", "third-division", "fourth-division", "conference", "national-league",
  "fa-cup", "league-cup", "carabao-cup", "charity-shield", "community-shield", "champions-league", "europa-league",
  "uefa-cup", "cup-winners-cup", "super-cup", "world-cup", "euros", "copa-america", "africa-cup", "asian-cup",
  "gold-cup", "nations-league", "olympics", "libertadores", "serie-a", "la-liga", "bundesliga", "ligue-one",
  "eredivisie", "primeira", "scottish-cup", "ballon-dor", "golden-boot", "golden-glove", "golden-ball", "trophy",
  "silverware", "medal", "ribbon", "lid", "cup", "plate", "final", "semi-final", "quarter-final", "last-sixteen",
  "group-stage", "knockout", "round", "third-round", "fourth-round", "fifth-round", "sixth-round", "preliminary",
  "qualifier", "qualifying", "group-of-death", "seeding", "draw-day", "pot-one", "pot-two", "tournament", "festival",
  "carnival", "showpiece", "curtain-raiser", "decider", "dead-rubber", "wembley", "hampden", "maracana", "azteca",
  "bernabeu", "camp-nou", "san-siro", "bombonera", "monumental", "centenario", "luzhniki", "mestalla",
  "olympiastadion", "westfalenstadion", "allianz-arena", "stade-de-france", "parc-des-princes", "de-kuip",
  "estadio-da-luz", "alvalade", "dragao", "san-paolo", "stadio-olimpico", "rose-bowl", "soldier-field", "la-cartuja",
  "windsor-park", "aviva-stadium", "ataturk", "soccer-city", "fnb-stadium", "lusail", "khalifa-stadium",
  "ali-bin-hamad", "rungrado-stadium", "bird-nest", "yokohama", "saitama", "seoul-stadium", "england", "scotland",
  "wales", "ireland", "northern-ireland", "france", "germany", "spain", "italy", "portugal", "netherlands",
  "holland", "belgium", "denmark", "sweden", "norway", "finland", "iceland", "poland", "ukraine", "russia",
  "croatia", "serbia", "bosnia", "slovenia", "slovakia", "czechia", "austria", "switzerland", "greece", "turkey",
  "romania", "bulgaria", "hungary", "albania", "georgia", "armenia", "israel", "brazil", "argentina", "uruguay",
  "chile", "colombia", "peru", "ecuador", "paraguay", "venezuela", "bolivia", "mexico", "usa", "canada",
  "costa-rica", "jamaica", "honduras", "panama", "haiti", "trinidad", "nigeria", "ghana", "cameroon", "senegal",
  "ivory-coast", "egypt", "morocco", "algeria", "tunisia", "south-africa", "mali", "zambia", "zimbabwe", "angola",
  "congo", "gabon", "japan", "korea", "australia", "iran", "saudi-arabia", "qatar", "china", "india", "thailand",
  "new-zealand", "fiji", "uzbekistan", "jordan", "iraq", "oman", "kuwait", "bahrain", "vietnam", "indonesia",
  "malaysia", "philippines", "luxembourg", "cyprus", "malta", "montenegro", "kosovo", "pele", "maradona", "cruyff",
  "beckenbauer", "zidane", "ronaldinho", "ronaldo", "messi", "neymar", "mbappe", "haaland", "modric", "xavi",
  "iniesta", "pirlo", "maldini", "baresi", "baggio", "totti", "buffon", "cannavaro", "zoff", "rossi", "platini",
  "eusebio", "puskas", "di-stefano", "garrincha", "zico", "socrates", "romario", "rivaldo", "kaka", "rivelino",
  "jairzinho", "carlos-alberto", "tostao", "bebeto", "cafu", "roberto-carlos", "dida", "taffarel", "batistuta",
  "crespo", "riquelme", "tevez", "aguero", "di-maria", "mascherano", "zanetti", "kempes", "passarella", "ardiles",
  "villa", "bergkamp", "van-basten", "gullit", "rijkaard", "koeman", "van-persie", "robben", "sneijder", "seedorf",
  "davids", "kluivert", "overmars", "stam", "de-boer", "van-der-sar", "cocu", "klinsmann", "matthaus", "voller",
  "brehme", "muller", "gerd-muller", "netzer", "ballack", "lahm", "schweinsteiger", "neuer", "kroos", "ozil",
  "klose", "podolski", "khedira", "hummels", "boateng", "kahn", "lehmann", "henry", "desailly", "thuram", "lizarazu",
  "blanc", "barthez", "deschamps", "trezeguet", "ribery", "benzema", "griezmann", "pogba", "kante", "lloris",
  "varane", "raul", "hierro", "puyol", "casillas", "ramos", "pique", "busquets", "torres", "fabregas", "silva",
  "mata", "alonso", "figo", "rui-costa", "deco", "pauleta", "nani", "cristiano", "pepe", "quaresma", "eder",
  "shevchenko", "blokhin", "zola", "vialli", "mancini", "vieri", "del-piero", "inzaghi", "nesta", "materazzi",
  "gattuso", "ambrosini", "drogba", "eto-o", "weah", "okocha", "yaya-toure", "salah", "mane", "mahrez", "aubameyang",
  "milla", "essien", "kanu", "yeboah", "abedi-pele", "pedro", "hazard", "lukaku", "de-bruyne", "courtois", "kompany",
  "vertonghen", "alderweireld", "witsel", "fellaini", "scifo", "ceulemans", "laudrup", "schmeichel", "elkjaer",
  "larsson", "ljungberg", "brolin", "ibrahimovic", "zlatan", "henke", "lato", "boniek", "lewandowski", "szczesny",
  "hagi", "stoichkov", "lechkov", "kostadinov", "prosinecki", "suker", "boban", "jarni", "rakitic", "perisic",
  "mandzukic", "olic", "srna", "moore", "charlton", "hurst", "banks", "stiles", "peters", "greaves", "hoddle",
  "lineker", "gascoigne", "shearer", "platt", "pearce", "seaman", "adams", "southgate", "owen", "beckham", "scholes",
  "gerrard", "lampard", "rooney", "kane", "sterling", "saka", "bellingham", "foden", "rice", "grealish", "walker",
  "stones", "maguire", "pickford", "trippier", "henderson", "mount", "sancho", "rashford", "shilton", "robson",
  "venables", "ramsey", "hodgson", "eriksson", "capello", "wright", "barnes", "waddle", "beardsley", "wilkins",
  "keegan", "barry", "milner", "walcott", "wilshere", "sturridge", "vardy", "alli", "dier", "lingard", "shaw",
  "chilwell", "banter", "chant", "song", "anthem", "scarf", "rattle", "flag", "banner", "tifo", "drum", "megaphone",
  "away-day", "away-end", "home-end", "kop", "worldie", "belter", "howler", "shocker", "stunner", "peach", "pearler",
  "pile-driver", "bobbler", "dodgy", "sitter", "easy-chance", "open-goal", "gimme", "lads", "mate", "pie", "bovril",
  "pint", "programme", "half-time-pie", "tea", "bacon-roll", "pasty", "chips", "curry", "season-ticket", "ticket",
  "tout", "queue", "coach-trip", "minibus", "train", "pub", "boozer", "atmosphere", "roar", "cheer", "boo", "jeer",
  "sing", "clap", "mexican-wave", "sing-up", "songbook", "singing-section", "clap-along", "stand-up", "sit-down",
  "bubbles", "bubble-machine", "pyro", "smoke-bomb", "confetti", "streamer", "ticker-tape", "scarf-aloft",
  "turned-up", "turn-out", "sell-out", "full-house", "capacity", "crowd", "gate", "attendance", "record-crowd",
  "sea-of-colour", "wall-of-noise", "cauldron", "fortress", "bear-pit", "field-of-dreams", "deadline-day",
  "transfer-window", "loan", "free-transfer", "bosman", "signing", "debut", "testimonial", "farewell", "retirement",
  "injury", "hamstring", "calf", "ankle", "groin", "knock", "fitness", "rehab", "pre-season", "friendly", "tour",
  "training", "academy", "youth", "reserves", "under-eighteens", "fixtures", "title-race", "run-in", "six-game-run",
  "unbeaten-run", "winning-streak", "losing-streak", "form", "slump", "purple-patch", "bogey-team", "new-signing",
  "record-signing", "homegrown", "wonderkid", "breakthrough", "breakout", "rising-star", "late-bloomer", "cult-hero",
  "fans-favourite", "highlights", "montage", "stunning", "sublime", "clinical", "ruthless", "relentless", "gritty",
  "gutsy", "plucky", "battling", "composed", "calm", "cool", "fearless", "fierce", "fiery", "tenacious", "tireless",
  "swift", "rapid", "nippy", "powerful", "skilful", "crafty", "cunning", "wily", "savvy", "classy", "elegant",
  "graceful", "silky", "smooth", "slick", "sharp", "deadly", "lethal", "ferocious", "mighty", "massive", "giant",
  "tiny", "nimble", "agile", "robust", "rugged", "solid", "steady", "dependable", "reliable", "consistent",
  "brilliant", "magnificent", "majestic", "glorious", "triumphant", "unbeaten", "invincible", "unstoppable",
  "unbreakable", "indomitable", "legendary", "historic", "iconic", "epic", "heroic", "dramatic", "breathless",
  "frantic", "frenzied", "electric", "thunderous", "deafening", "roaring", "rousing", "stirring", "inspiring",
  "uplifting", "emotional", "tearful", "joyful", "jubilant", "ecstatic", "delirious", "floodlit", "night-match",
  "midweek", "matchday-morning", "cold-night", "wet-tuesday", "windy-wednesday", "goalmouth", "scramble", "melee",
  "pinball", "ricochet", "fluke", "cobwebs", "post-and-bar", "goal-line", "technology", "offside-line",
  "semi-automated", "linesman-flag", "flag-up", "onside", "level", "saved-penalty", "retaken", "re-taken",
  "penalty-miss", "penalty-hero", "shootout-hero", "shootout-loss", "sudden-death", "late-show", "dramatic-finish",
  "heartbreak", "agony", "ecstasy", "relief", "joy", "despair", "delight", "tunnel-bust-up", "touchline-ban",
  "post-match", "press-conference", "interview", "flash-interview", "free-scoring", "high-scoring", "low-scoring",
  "goal-fest", "goal-machine", "goal-poacher", "goal-hanger", "tap-in-merchant", "hard-man", "ball-winner",
  "enforcer", "destroyer", "midfield-general", "dictator", "conductor", "orchestrator", "wizard", "magician",
  "artist", "craftsman", "stopwatch", "timekeeper", "fourth-official", "fifth-official", "goal-judge",
  "match-official", "match-report", "line-up", "team-news", "starting-eleven", "starting-xi", "bench-warmers",
  "substitution", "tactical-switch", "half-time-talk", "rollicking", "pep-talk", "captains-armband",
  "armband-wearer", "skippers-speech", "trophy-lift", "trophy-parade", "open-top-bus", "victory-parade",
  "homecoming", "celebration", "knee-slide", "shush", "salute", "crest-kiss", "badge-kiss", "pile-on", "huddle",
  "group-hug", "high-five", "fist-pump", "roar-of-delight", "no-celebration", "fifty-fifty", "second-ball",
  "loose-ball", "aerial-duel", "duel", "challenge", "contest", "battle", "scrap", "tussle", "skirmish",
  "wing-wizard", "flying-winger", "tricky-winger", "marauding", "rock", "colossus", "giant-stopper", "shot-stopper",
  "penalty-saver", "last-man", "predator", "sniper", "marksman", "assassin", "hitman", "gunslinger", "nutmegger",
  "tormentor", "terrier", "bulldog", "warrior", "soldier", "gladiator", "inswinger", "outswinger", "whipped-cross",
  "driven-cross", "floated-cross", "low-cross", "early-cross", "deep-cross", "volleyed-cross", "headed-clearance",
  "last-ditch", "heroic-block", "desperate-lunge", "warm-up", "warm-down", "stretching", "drills", "rondo", "rondos",
  "small-sided", "possession-game", "conditioning", "bleep-test", "yo-yo-test", "fitness-test", "gym", "weights",
  "ice-bath", "cryotherapy", "recovery", "massage", "strapping", "bandage", "cast", "crutches", "scan", "surgery",
  "operation", "ligament", "cartilage", "hamstring-strain", "stamina", "pace", "acceleration", "agility", "strength",
  "power", "endurance", "coordination", "reaction", "vision", "awareness", "anticipation", "transfer-fee",
  "release-clause", "buy-out", "wage", "salary", "bonus", "contract", "extension", "renewal", "agent", "adviser",
  "deal", "medical", "unveiling", "shirt-unveil", "photo-call", "press-day", "fan-forum", "supporters-trust",
  "membership", "sponsorship", "kit-launch", "shirt-deal", "stadium-naming", "naming-rights", "broadcast",
  "highlights-show", "phone-in", "podcast", "fanzine", "programme-notes", "editorial", "column", "back-page",
  "headline", "rumour", "gossip", "speculation", "transfer-saga", "u-turn", "about-turn", "last-gasp",
  "deadline-deal", "ninety-minutes", "ninetieth-minute", "injury-time-goal", "added-minutes", "stoppage-minutes",
  "sixty-fifth", "seventy-fifth", "eighty-eighth", "ninety-first", "opening-day", "final-day", "cup-final-day",
  "semi-final-day",
];

export default FOOTBALL_POOL;
